# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[test]
# ⚠️ KNOWN LIMITATION IN BUN 1.3.0
# These exclude patterns do NOT work - Bun test discovers ALL .spec.ts files
# in the project tree regardless of these exclude patterns or directory filters.
#
# IMPACT: Running `bun test:unit` (which targets src/ scripts/ directories) will
# still discover 4 Playwright E2E spec files that cause test failures:
#   - specs/app/pages/scripts/scripts.spec.ts
#   - specs/app/pages/scripts/external-scripts/external-scripts.spec.ts
#   - specs/app/pages/scripts/inline-scripts/inline-scripts.spec.ts
#   - specs/app/pages/scripts/features/features.spec.ts
#
# ERROR: "Playwright Test did not expect test.describe() to be called here"
# (Bun test runner is incompatible with Playwright's test.describe() API)
#
# CURRENT WORKAROUND: Accept the 4 failures when running bun test:unit
# - 681 unit tests pass correctly
# - 4 Playwright specs fail (expected, can be ignored)
# - CI/quality checks should use `bun run quality` which handles this properly
#
# FUTURE FIX: When Bun fixes exclude support, or rename the 4 spec files to
# use a non-colliding pattern (e.g., *.e2e.ts instead of *.spec.ts)
#
# These patterns are kept for documentation and future Bun versions:
exclude = [
  "specs/**/*.spec.ts",
  "specs/**/*.spec.tsx",
]
