# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[test]
# ℹ️ PATTERN FILTER APPROACH (NO EXCLUDE NEEDED)
# The project uses pattern filters to run unit tests without conflicts:
#   Command: bun test --concurrent .test.ts .test.tsx
#   Result: ONLY files matching .test.ts or .test.tsx are executed
#
# PATTERN MATCHING BEHAVIOR:
# - `.test.ts` and `.test.tsx` are treated as PATTERN FILTERS (NOT file paths)
# - Bun searches the entire project and matches ONLY files containing these patterns
# - `.spec.ts` files (Playwright E2E tests) are automatically excluded
# - No need for exclude patterns when using pattern filters
#
# RESULT:
# - ✅ 681 unit tests pass
# - ✅ 0 Playwright spec files loaded
# - ✅ No "test.describe is not a function" errors
# - ✅ Clean separation: .test.ts = unit tests, .spec.ts = E2E tests
#
# WHY EXCLUDE PATTERNS ARE NOT USED:
# Pattern filters (bun test .test.ts .test.tsx) provide better isolation than
# exclude patterns. This approach is more explicit and prevents accidental
# discovery of incompatible test files.
#
# DOCUMENTATION: These exclude patterns are kept for reference only
# and are NOT relied upon for test isolation:
exclude = [
  "specs/**/*.spec.ts",
  "specs/**/*.spec.tsx",
]
