name: TDD Auto-Merge Manager

on:
  pull_request:
    types: [opened, reopened]

# Security: Define minimal required permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: 🔄 Enable Auto-Merge for TDD PRs
    runs-on: ubuntu-latest
    # Only run for TDD automation PRs
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'tdd-automation')

    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            // Check if PR is from TDD automation
            const isTddPr = pr.labels.some(l => l.name === 'tdd-automation');
            const isReadyForReview = pr.labels.some(l => l.name === 'ready-for-review');

            if (!isTddPr || !isReadyForReview) {
              console.log('PR not ready for auto-merge');
              return;
            }

            try {
              // Enable auto-merge with squash method
              const result = await github.graphql(`
                mutation EnableAutoMerge($pullRequestId: ID!) {
                  enablePullRequestAutoMerge(input: {
                    pullRequestId: $pullRequestId,
                    mergeMethod: SQUASH
                  }) {
                    pullRequest {
                      autoMergeRequest {
                        enabledAt
                        mergeMethod
                      }
                    }
                  }
                }
              `, {
                pullRequestId: pr.node_id
              });

              console.log('✅ Auto-merge enabled for PR #' + pr.number);

              // Add comment explaining auto-merge
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `## 🔄 Auto-Merge Enabled

                This TDD automation PR will automatically merge when all checks pass:
                - ✅ All tests passing
                - ✅ Code quality checks (ESLint, TypeScript)
                - ✅ No merge conflicts

                **Note**: If you need to review before merge, disable auto-merge:
                \`\`\`bash
                gh pr merge --disable-auto --repo ${context.repo.owner}/${context.repo.repo} ${pr.number}
                \`\`\`

                [View workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
              });
            } catch (error) {
              console.error('Failed to enable auto-merge:', error);

              // Fall back to manual merge reminder
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `## ⚠️ Auto-Merge Not Available

                Auto-merge could not be enabled. This PR requires manual review and merge.

                Possible reasons:
                - Branch protection rules not configured
                - Auto-merge not enabled in repository settings
                - Insufficient permissions

                Please review and merge manually when all checks pass.`
              });
            }

      - name: Label PR for monitoring
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['auto-merge-enabled']
            });
