name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "Workflow dispatch works! Input: ${{ github.event.inputs.test_input }}"
